version: '3'
services:
    web:
        build: .
        command: >
            bash -c "python3 manage.py migrate
            && python3 manage.py loaddata fixtures/offices.json
            && python3 manage.py loaddata fixtures/rooms.json
            && python3 manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            - db
    db:
        image: 'postgres:latest'
        expose:
            - "5432"
        environment:
            POSTGRES_USER: ananevich
            POSTGRES_PASSWORD: qwerty
            POSTGRES_DB: office
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
